# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AddLateralAtWye
                                 A QGIS plugin
 This plugin adds lateral lines from wyes along a main
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-19
        copyright            : (C) 2019 by Ed B
        email                : boesiii@yahoo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AddLateralAtWye class from file AddLateralAtWye.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .add_lateral_at_wye import AddLateralAtWye
    return AddLateralAtWye(iface)
